// Auto-generated kbuild configuration module
//
// This module provides access to configuration constants from .config file
// These constants are generated by cargo-kbuild at build time

#![no_std]

// Include the generated config.rs file
include!(env!("CONFIG_RS_PATH"));
